yolo_model:

        config_file:
                name: yolov3_auv_sim_gate_obstacle_v1.cfg
        weight_file:
                nane: yolov3_auv_sim_gate_obstacle_v1.backup
        threshold:
                value: 0.4
        detection_classes:
                names:
                        - gate_green
                        - gate_red
                        - gate_mid
                        - obstacle
