yolo_model:

  config_file:
    name: itr1.cfg
  weight_file:
    name: itr1.weights
  threshold:
    value: 0.4
  detection_classes:
    names:
      - gate_green
      - gate_red
      - gate_mid
      - obstacle
